name: deploy

on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu:24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Stop and Remove Spring Docker Container..."
          docker stop steam-discount
          docker rm steam-discount

          echo "Pulling latest code from repository..."
          cd /home/ubuntu/spring/git_hub/steam-discount
          git pull

          echo "Building the application..."
          cd /home/ubuntu/spring/git_hub/steam-discount/steam-discount
          bash gradlew clean build

          echo "Building Dockerfile..."
          cd /home/ubuntu
          docker build -f Dockerfile.server -t ubuntu:server .

          echo "Starting Spring Docker Container..."
          docker run -d --name steam-discount -p 8443:8443 --network my-network --env-file .env ubuntu:server
