name: deploy

on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Stopping existing Spring application..."
          sudo systemctl stop steam-discount

          echo "Pulling latest code from repository..."
          cd /home/ubuntu/react
          git pull

          echo "Building the application..."
          cd steam-discount
          bash gradlew clean build

          echo "Starting the application..."
          sudo systemctl start steam-discount
