name: deploy  #이름

on:  # main branche가 psuh 되었을 때 실행
  push:
    branches:
    - main

jobs:  #실행할 명령어
  SSH:
    runs-on: ubuntu-latest  #우분투 최신버전

    steps:
      - uses: actions/checkout@v3  #레파지토리 참고
      - name: ssh to ec2  #이름
        uses: appleboy/ssh-action@master  #appleboy/ssh-action@master 사용
        with:
          key: ${{ secrets.SSH_KEY }} # 내가 변수로 저장한 pem key
          host: ${{ secrets.HOST }} # 내가 변수로 저장한 ip
          username: ${{ secrets.USER }} # 내가 변수로 저장한 User
          script: |
            cd spring/git_hub/steam-discount
            git pull
            cd steam-discount
            gradlew build
            
